site_name: BHoM wiki

theme:
  name: material
  logo: img/logos/logo.png
  favicon: img/logos/logo.png
  palette:
    primary: white
    accent: pink

  features:
    - navigation.tracking

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences