site_name: BHoM documentation

theme:
  name: material
  logo: img/logos/logo.png
  favicon: img/logos/logo.png
  palette:
    primary: white
    accent: pink

  features:
    - navigation.tracking

plugins:
  - search
  - awesome-pages #allows to customise the ordering of pages

markdown_extensions:
  # Wider support to markdown symbols
  - pymdownx.betterem
  
  # Code syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Mathjax support
  - pymdownx.arithmatex:
      generic: true

extra_javascript: 
  # Also required for Mathjax support
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js