site_name: BHoM wiki

theme:
  name: material
  logo: img/logos/logo.png
  favicon: img/logos/logo.png
  palette:
    primary: white
    accent: pink

  features:
    - navigation.tracking

plugins:
  - search
  - awesome-pages